### ISSUE TITLE
设备二次验证好像又失效了

### ISSUE THREAD

**Issue by Caesium-133** [fengyuecanzhu/Sdu-Seat#2]
config里面已经按说明配置了设备ID，运行jar时发生
```
ERROR kotlin.Unit
java.util.concurrent.ExecutionException: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at me.fycz.sduseat.Main.loginAndGetSeats(Main.kt:112)
        at me.fycz.sduseat.Main.loginAndGetSeats$default(Main.kt:103)
        at me.fycz.sduseat.Main.main(Main.kt:78)
Caused by: me.fycz.sduseat.AuthException: 设备验证失败：需要进行二次验证
[2023-09-04 12:32:44]:INFO 请等待到2023-09-05 12:30:00
[2023-09-04 12:32:45]:INFO
-------------获取2023-09-05 08:00-22:30时间段座位-------------
成功获取到3个预设座位信息：
```
麻烦了

**Comment by fengyuecanzhu** [comment]
你确定获取id的时候勾选了信任此设备？

**Comment by Caesium-133** [comment]
> 你确定获取id的时候勾选了信任此设备？

常用浏览器一直是可以直接登录的，换了个新浏览器勾选了信任此设备后解决了，感谢大佬！
